[avx]
name = "AVX"
desc = "Advanced Vector Extensions"
more = "Intel chips support"

[adc]
name = "mnemonic: ADC"
desc = "ADd with Carry"

[adx]
name = "mnemonic: ADX"
desc = "Multi-Precision Add-Carry Instruction Extensions"
