[cs]
name = "CS"
desc = "Code Segment register"
see = ['DS', 'SS', 'ES']

[cf]
name = "CF"
desc = "Carry Flag (Bit 1)"

[cmpb]
name = "cmpb"
desc = "Compare Byte"
more = "A comparison instruction that compares two 8-bit operands and sets the condition flags accordingly"
see = ['cmpw', 'cmpl']

[cmpw]
name = "cmpw"
desc = "Compare Word"
more = "A comparison instruction that compares two 16-bit operands and sets the condition flags accordingly"
see = ['cmpb', 'cmpl']

[cmpl]
name = "cmpl"
desc = "Compare Longword"
more = "A comparison instruction that compares two 32-bit operands and sets the condition flags accordingly"
see = ['cmpb', 'cmpw']

[cld]
name = "cld"
desc = "Clear the Direction flag"
more = "The DF flag controls whether string operations increment or decrement the index registers (SI and/or DI)"

[cli]
name = "cli"
desc = "Clear the Interrupt flag"
more = "Clears the 'Interrupt Flag' (IF) bit in the FLAGS register, this tells the CPU to temporarily ignore hardware interrupts"
see = 'sti'
