[lea]
name = "lea"
desc = "Load Effective Address"
more = "Load the effective address of the operand into the destination register. The effective address is the actual memory location that will be accessed when the operand is used"

[lidt]
name = "lidt"
desc = "Load the IDTR register"
see = [ 'IDTR', 'IDT']

[lgdt]
name = "LGDT"
desc = "Load the GDTR register"
see = ['GDTR', 'GDT']
